"""Add log_messages to AnalysisRun

Revision ID: 20251028_161016
Revises:
Create Date: 2025-10-28 16:10:16.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20251028_161016'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_run', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log_messages', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_run', schema=None) as batch_op:
        batch_op.drop_column('log_messages')

    # ### end Alembic commands ###
